import type { CSSProperties } from 'react'
import type { SxProps, Theme } from '@mui/material/styles'

export const imageFilterStyle: CSSProperties = {
  objectFit: 'cover',
  filter: 'saturate(0.9) contrast(1.05) brightness(0.95) hue-rotate(-8deg)',
}

const styles: Record<string, SxProps<Theme>> = {
  main: {
    bgcolor: 'background.default',
  },
  heroSection: {
    position: 'relative',
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    color: 'common.white',
    overflow: 'hidden',
  },
  heroImageWrap: {
    position: 'absolute',
    inset: 0,
    zIndex: 0,
  },
  heroDarkOverlay: {
    position: 'absolute',
    inset: 0,
    background:
      'linear-gradient(180deg, rgba(255,255,255,0.08) 0%, rgba(7,11,18,0.42) 80%)',
    zIndex: 1,
  },
  heroAuroraOverlay: {
    position: 'absolute',
    inset: 0,
    background:
      'radial-gradient(1200px 420px at 15% 10%, rgba(124,214,255,0.12) 0%, rgba(124,214,255,0) 70%), radial-gradient(900px 320px at 80% 5%, rgba(123,237,190,0.1) 0%, rgba(123,237,190,0) 65%)',
    mixBlendMode: 'screen',
    opacity: 0.45,
    zIndex: 1,
    pointerEvents: 'none',
  },
  heroContainer: {
    position: 'relative',
    zIndex: 2,
  },
  heroStack: {
    maxWidth: 1280,
    textAlign: { xs: 'center', md: 'left' },
  },
  heroChip: {
    bgcolor: 'white',
    color: 'var(--accent-ice)',
    border: '1px solid rgba(47,143,212,0.3)',
    width: 'fit-content',
    fontWeight: 600,
  },
  heroTitle: {
    fontSize: { xs: '2.5rem', sm: '3.1rem', md: '5rem' },
    letterSpacing: { xs: '-0.02em', md: '-0.03em' },
    lineHeight: { xs: 1.1, md: 1.05 },
    textShadow: '0 14px 32px rgba(7,11,18,0.45)',
  },
  heroLead: {
    fontSize: { xs: '1rem', sm: '1.1rem', md: '1.3rem' },
    letterSpacing: '0.01em',
    lineHeight: 1.7,
    color: '#f1f6ff',
    textShadow: '0 10px 24px rgba(7,11,18,0.35)',
  },
  heroNote: {
    fontSize: { xs: '0.9rem', md: '1rem' },
    color: 'rgba(239, 246, 255, 0.82)',
  },
  heroButtons: {
    alignItems: { xs: 'stretch', sm: 'center' },
  },
  heroPrimaryButton: {
    bgcolor: '#7fd1ff',
    color: '#04111f',
    fontWeight: 700,
    px: 4,
    py: 1.5,
    '&:hover': { bgcolor: '#a5e3ff' },
  },
  heroSecondaryButton: {
    borderColor: 'rgba(255,255,255,0.6)',
    color: 'common.white',
    px: 4,
    py: 1.5,
    '&:hover': { borderColor: '#2f8fd4', color: '#2f8fd4' },
  },
  aboutSection: {
    py: { xs: 10, md: 14 },
    position: 'relative',
    bgcolor: 'var(--bg-section-base)',
    boxShadow:
      'inset 0 1px 0 rgba(255,255,255,0.85), inset 0 -1px 0 rgba(12,34,60,0.08)',
    '&::before': {
      content: '""',
      position: 'absolute',
      top: { xs: -40, md: -60 },
      left: 0,
      right: 0,
      height: { xs: 60, md: 90 },
      background:
        'linear-gradient(180deg, rgba(255,255,255,0) 0%, rgba(246,250,255,0.9) 100%)',
    },
    '&::after': {
      content: '""',
      position: 'absolute',
      inset: 0,
      background:
        'radial-gradient(ellipse 100% 62% at 50% 0%, rgba(186, 215, 241, 0.14) 0%, transparent 60%), radial-gradient(ellipse 85% 42% at 18% 100%, rgba(164, 197, 228, 0.1) 0%, transparent 58%)',
      pointerEvents: 'none',
      zIndex: 0,
    },
  },
  aboutIntro: {
    maxWidth: '100%',
    mb: 6,
    position: 'relative',
    zIndex: 1,
  },
  aboutTitle: {
    fontSize: { xs: '2.3rem', md: '3.2rem' },
  },
  aboutLead: {
    color: '#2f4257',
    fontSize: '1.1rem',
  },
  aboutGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: 'repeat(3, 1fr)' },
    gap: 3,
    position: 'relative',
    zIndex: 1,
  },
  aboutCard: {
    bgcolor: 'var(--glass)',
    border: '1px solid var(--glass-border)',
    borderRadius: 4,
    boxShadow: 'var(--glass-shadow)',
    backdropFilter: 'blur(16px)',
    height: '100%',
  },
  aboutCardTitle: {
    fontSize: '1.5rem',
  },
  aboutCardBody: {
    color: '#304357',
  },
  aboutIconChip: {
    width: 64,
    height: 64,
    borderRadius: '20px',
    display: 'grid',
    placeItems: 'center',
    bgcolor: 'rgba(124, 214, 255, 0.18)',
    border: '1px solid rgba(47,143,212,0.25)',
    boxShadow: '0 12px 24px rgba(12, 34, 60, 0.12)',
  },
  aboutIcon: {
    fontSize: 36,
    color: 'var(--accent-ice)',
  },
  threatSection: {
    py: { xs: 10, md: 14 },
    position: 'relative',
    background:
      'linear-gradient(180deg, var(--bg-section-warm) 0%, #fff6ef 52%, var(--bg-section-sand) 100%)',
    boxShadow:
      'inset 0 1px 0 rgba(255,255,255,0.75), inset 0 -1px 0 rgba(12,34,60,0.08)',
    '&::before': {
      content: '""',
      position: 'absolute',
      inset: 0,
      background:
        'radial-gradient(ellipse 84% 52% at 22% 20%, rgba(231,111,81,0.07) 0%, transparent 62%), radial-gradient(ellipse 66% 42% at 82% 82%, rgba(245,158,11,0.05) 0%, transparent 56%)',
      pointerEvents: 'none',
      zIndex: 0,
    },
  },
  threatTopRow: {
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    gap: 5,
    alignItems: 'stretch',
    mb: 8,
  },
  threatStatCard: {
    flex: 1,
    bgcolor: 'rgba(255, 241, 232, 0.85)',
    borderRadius: 5,
    border: '1px solid rgba(231,111,81,0.35)',
    boxShadow: 'var(--glass-shadow)',
    backdropFilter: 'blur(12px)',
  },
  threatStatContent: {
    p: 5,
  },
  threatStatIcon: {
    fontSize: 56,
    color: '#e76f51',
  },
  threatStatTitle: {
    fontSize: '3rem',
  },
  threatStatLead: {
    color: '#7a5b51',
    fontSize: '1.2rem',
  },
  threatImageBox: {
    position: 'relative',
    flex: 1,
    borderRadius: 5,
    overflow: 'hidden',
    minHeight: 360,
    border: '1px solid var(--glass-border)',
    boxShadow: 'var(--glass-shadow)',
  },
  threatImageOverlay: {
    position: 'absolute',
    inset: 0,
    background: 'linear-gradient(180deg, rgba(255,255,255,0) 0%, rgba(255,255,255,0.35) 100%)',
  },
  threatCardsGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: 'repeat(3, 1fr)' },
    gap: 3,
  },
  threatCard: {
    bgcolor: 'var(--glass)',
    borderRadius: 4,
    border: '1px solid var(--glass-border)',
    boxShadow: 'var(--glass-shadow)',
    backdropFilter: 'blur(14px)',
    height: '100%',
  },
  threatCardTitle: {
    fontSize: '1.5rem',
  },
  threatCardBody: {
    color: '#304357',
  },
  threatIconChipWarm: {
    width: 60,
    height: 60,
    borderRadius: '18px',
    display: 'grid',
    placeItems: 'center',
    bgcolor: 'rgba(231, 111, 81, 0.12)',
    border: '1px solid rgba(231,111,81,0.3)',
    boxShadow: '0 10px 22px rgba(231, 111, 81, 0.16)',
  },
  threatIconWarm: {
    fontSize: 32,
    color: '#e76f51',
  },
  threatIconChipCool: {
    width: 60,
    height: 60,
    borderRadius: '18px',
    display: 'grid',
    placeItems: 'center',
    bgcolor: 'rgba(47, 143, 212, 0.12)',
    border: '1px solid rgba(47,143,212,0.28)',
    boxShadow: '0 10px 22px rgba(47, 143, 212, 0.16)',
  },
  threatIconCool: {
    fontSize: 32,
    color: '#2f8fd4',
  },
  threatIconChipSun: {
    width: 60,
    height: 60,
    borderRadius: '18px',
    display: 'grid',
    placeItems: 'center',
    bgcolor: 'rgba(245, 158, 11, 0.12)',
    border: '1px solid rgba(245,158,11,0.3)',
    boxShadow: '0 10px 22px rgba(245, 158, 11, 0.16)',
  },
  threatIconSun: {
    fontSize: 32,
    color: '#f59e0b',
  },
  dataSection: {
    py: { xs: 10, md: 14 },
    position: 'relative',
    background:
      'linear-gradient(180deg, var(--bg-section-cool) 0%, var(--bg-section-cool-soft) 52%, var(--bg-section-frost) 100%)',
    boxShadow:
      'inset 0 1px 0 rgba(255,255,255,0.85), inset 0 -1px 0 rgba(12,34,60,0.08)',
    '&::before': {
      content: '""',
      position: 'absolute',
      inset: 0,
      background:
        'radial-gradient(ellipse 118% 68% at 28% 18%, rgba(124, 214, 255, 0.1) 0%, transparent 64%), radial-gradient(ellipse 92% 52% at 74% 82%, rgba(47, 143, 212, 0.06) 0%, transparent 56%)',
      pointerEvents: 'none',
      zIndex: 0,
    },
    '&::after': {
      content: '""',
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: { xs: -40, md: -60 },
      height: { xs: 70, md: 100 },
      background:
        'linear-gradient(180deg, rgba(227,238,252,0.82) 0%, rgba(255,255,255,0) 100%)',
      zIndex: 0,
    },
  },
  dataHeader: {
    textAlign: 'center',
    mb: 6,
    position: 'relative',
    zIndex: 1,
  },
  dataTitle: {
    fontSize: { xs: '2.5rem', md: '3.4rem' },
  },
  dataLead: {
    color: '#2f4257',
  },
  dataGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: 'repeat(2, 1fr)' },
    gap: { xs: 2.5, md: 3 },
    position: 'relative',
    zIndex: 1,
  },
  dataImageBox: {
    position: 'relative',
    borderRadius: 5,
    overflow: 'hidden',
    minHeight: { xs: 240, sm: 280, md: 320 },
    boxShadow: 'var(--glass-shadow)',
  },
  dataImageOverlay: {
    position: 'absolute',
    inset: 0,
    background: 'linear-gradient(180deg, rgba(10,20,30,0.1) 0%, rgba(10,20,30,0.9) 100%)',
    display: 'flex',
    alignItems: 'flex-end',
  },
  dataStatCard: {
    p: 4,
    bgcolor: 'rgba(7,11,18,0.55)',
    borderRadius: 3,
    mb: 3,
    ml: 3,
    border: '1px solid rgba(255,255,255,0.15)',
    maxWidth: 360,
  },
  dataStatNumber: {
    color: '#eef6ff',
    fontSize: '2.5rem',
    textShadow: '0 6px 16px rgba(3,8,14,0.5)',
  },
  dataStatLabel: {
    color: '#eef6ff',
    textShadow: '0 6px 16px rgba(3,8,14,0.45)',
  },
  dataMapSection: {
    mt: 6,
    position: 'relative',
    zIndex: 1,
  },
  dataMapTitle: {
    fontSize: { xs: '1.8rem', md: '2.2rem' },
    mb: 2,
  },
  dataMapLead: {
    color: '#2f4257',
    mb: 4,
  },
  dataMapBox: {
    position: 'relative',
    borderRadius: 5,
    overflow: 'hidden',
    border: '1px solid var(--glass-border)',
    boxShadow: 'var(--glass-shadow)',
    p: { xs: 2, md: 3 },
    bgcolor: 'rgba(255,255,255,0.7)',
    backdropFilter: 'blur(8px)',
  },
  dataOverlayMapContainer: {
    position: 'relative',
    borderRadius: 5,
    overflow: 'hidden',
    border: '1px solid var(--glass-border)',
    boxShadow: 'var(--glass-shadow)',
    height: { xs: 320, sm: 400, md: 480 },
  },
  dataOverlayMapSvg: {
    position: 'absolute',
    inset: 0,
    pointerEvents: 'auto',
    zIndex: 10,
  },
  dataPopulationMapBox: {
    position: 'relative',
    borderRadius: 5,
    overflow: 'hidden',
    border: '1px solid var(--glass-border)',
    boxShadow: 'var(--glass-shadow)',
    bgcolor: '#f5f9fc',
    height: { xs: 280, sm: 380, md: 500 },
  },
  dataMapLegend: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: { xs: 1.5, md: 3 },
    mt: 2,
  },
  dataMapCaption: {
    mt: 2,
    color: '#5a7a99',
    fontSize: '0.9rem',
    textAlign: 'center',
  },
  dataRealMapBox: {
    mt: 4,
    borderRadius: 5,
    overflow: 'hidden',
    border: '1px solid var(--glass-border)',
    boxShadow: 'var(--glass-shadow)',
    height: { xs: 280, sm: 360, md: 420 },
    '& iframe': {
      width: '100%',
      height: '100%',
      border: 0,
    },
  },
  importanceSection: {
    py: { xs: 10, md: 14 },
    position: 'relative',
    background:
      'linear-gradient(180deg, var(--bg-section-sand) 0%, #fff9f1 52%, var(--bg-section-base) 100%)',
    boxShadow:
      'inset 0 1px 0 rgba(255,255,255,0.8), inset 0 -1px 0 rgba(12,34,60,0.08)',
    '&::before': {
      content: '""',
      position: 'absolute',
      top: { xs: -50, md: -70 },
      left: 0,
      right: 0,
      height: { xs: 80, md: 120 },
      background:
        'linear-gradient(180deg, rgba(255,255,255,0) 0%, rgba(247,250,255,0.86) 100%)',
      zIndex: 0,
    },
    '&::after': {
      content: '""',
      position: 'absolute',
      inset: 0,
      background:
        'radial-gradient(ellipse 102% 62% at 52% 32%, rgba(255, 224, 184, 0.17) 0%, transparent 58%), radial-gradient(ellipse 82% 52% at 12% 72%, rgba(255, 239, 214, 0.14) 0%, transparent 56%)',
      pointerEvents: 'none',
      zIndex: 0,
    },
  },
  importanceCard: {
    bgcolor: 'var(--glass-strong)',
    borderRadius: 6,
    border: '1px solid var(--glass-border)',
    boxShadow: 'var(--glass-shadow)',
    backdropFilter: 'blur(16px)',
    position: 'relative',
    zIndex: 1,
  },
  importanceCardContent: {
    p: { xs: 4, md: 8 },
  },
  importanceIcon: {
    fontSize: 56,
    color: '#f59e0b',
  },
  importanceTitle: {
    fontSize: { xs: '2.4rem', md: '3.2rem' },
    textAlign: 'center',
  },
  importanceGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: 'repeat(3, 1fr)' },
    gap: { xs: 4, md: 5 },
    width: '100%',
    justifyItems: 'stretch',
    position: 'relative',
    zIndex: 1,
  },
  importanceItemCard: {
    p: { xs: 2.5, md: 3 },
    width: '100%',
    maxWidth: 320,
    mx: 'auto',
    minHeight: { xs: 'auto', md: 220 },
    bgcolor: 'rgba(255,255,255,0.8)',
    borderRadius: 4,
    border: '1px solid rgba(47,143,212,0.16)',
    boxShadow: '0 10px 26px rgba(12,34,60,0.08)',
    backdropFilter: 'blur(8px)',
  },
  importanceItemIcon: {
    fontSize: { xs: 40, md: 48 },
    color: '#2f8fd4',
  },
  importanceItemTitle: {
    fontSize: { xs: '1.1rem', sm: '1.2rem', md: '1.3rem' },
    lineHeight: 1.4,
    fontWeight: 600,
    textAlign: 'left',
    width: '100%',
  },
  importanceItemText: {
    color: '#304357',
    fontSize: { xs: '0.9rem', md: '1rem' },
    textAlign: 'left',
    width: '100%',
  },
  actionSection: {
    py: { xs: 10, md: 14 },
    position: 'relative',
    background:
      'linear-gradient(180deg, var(--bg-section-mint) 0%, #edf9f3 52%, var(--bg-section-base) 100%)',
    boxShadow:
      'inset 0 1px 0 rgba(255,255,255,0.8), inset 0 -1px 0 rgba(12,34,60,0.08)',
    '&::before': {
      content: '""',
      position: 'absolute',
      inset: 0,
      background:
        'radial-gradient(ellipse 110% 66% at 42% 24%, rgba(76, 175, 80, 0.08) 0%, transparent 58%), radial-gradient(ellipse 86% 46% at 60% 76%, rgba(109, 181, 138, 0.07) 0%, transparent 55%)',
      pointerEvents: 'none',
      zIndex: 0,
    },
    '&::after': {
      content: '""',
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: { xs: -50, md: -70 },
      height: { xs: 90, md: 120 },
      background:
        'linear-gradient(180deg, rgba(255,255,255,0) 0%, rgba(232,241,252,0.86) 100%)',
      zIndex: 0,
    },
  },
  actionHeader: {
    textAlign: 'center',
    mb: 6,
    position: 'relative',
    zIndex: 1,
  },
  actionTitle: {
    fontSize: { xs: '2.5rem', md: '3.4rem' },
  },
  actionLead: {
    color: '#2f4257',
  },
  actionGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: 'repeat(2, 1fr)' },
    gap: 3,
    position: 'relative',
    zIndex: 1,
  },
  actionCard: {
    bgcolor: 'var(--glass)',
    borderRadius: 5,
    border: '1px solid var(--glass-border)',
    boxShadow: 'var(--glass-shadow)',
    backdropFilter: 'blur(14px)',
    height: '100%',
  },
  actionCardContent: {
    p: 4,
  },
  actionCardTitle: {
    fontSize: '1.6rem',
  },
  actionCardBody: {
    color: '#304357',
    whiteSpace: 'pre-line',
  },
  actionIconChipGreen: {
    width: 66,
    height: 66,
    borderRadius: '22px',
    display: 'grid',
    placeItems: 'center',
    bgcolor: 'rgba(76, 175, 80, 0.15)',
    border: '1px solid rgba(76,175,80,0.3)',
    boxShadow: '0 12px 26px rgba(76, 175, 80, 0.18)',
  },
  actionIconGreen: {
    fontSize: 36,
    color: '#4caf50',
  },
  actionIconChipBlue: {
    width: 66,
    height: 66,
    borderRadius: '22px',
    display: 'grid',
    placeItems: 'center',
    bgcolor: 'rgba(47, 143, 212, 0.15)',
    border: '1px solid rgba(47,143,212,0.3)',
    boxShadow: '0 12px 26px rgba(47, 143, 212, 0.18)',
  },
  actionIconBlue: {
    fontSize: 36,
    color: '#2f8fd4',
  },
  actionIconChipSteel: {
    width: 66,
    height: 66,
    borderRadius: '22px',
    display: 'grid',
    placeItems: 'center',
    bgcolor: 'rgba(47, 111, 159, 0.15)',
    border: '1px solid rgba(47,111,159,0.3)',
    boxShadow: '0 12px 26px rgba(47, 111, 159, 0.18)',
  },
  actionIconSteel: {
    fontSize: 36,
    color: '#2f6f9f',
  },
  actionIconChipAmber: {
    width: 66,
    height: 66,
    borderRadius: '22px',
    display: 'grid',
    placeItems: 'center',
    bgcolor: 'rgba(245, 158, 11, 0.15)',
    border: '1px solid rgba(245,158,11,0.3)',
    boxShadow: '0 12px 26px rgba(245, 158, 11, 0.18)',
  },
  actionIconAmber: {
    fontSize: 36,
    color: '#f59e0b',
  },
  pbiSection: {
    py: { xs: 10, md: 14 },
    position: 'relative',
    background:
      'linear-gradient(180deg, var(--bg-section-cool-soft) 0%, #edf5ff 52%, var(--bg-section-frost) 100%)',
    boxShadow:
      'inset 0 1px 0 rgba(255,255,255,0.85), inset 0 -1px 0 rgba(12,34,60,0.08)',
    '&::before': {
      content: '""',
      position: 'absolute',
      inset: 0,
      background:
        'radial-gradient(ellipse 92% 62% at 20% 20%, rgba(124, 214, 255, 0.1) 0%, transparent 58%), radial-gradient(ellipse 82% 52% at 80% 80%, rgba(47, 143, 212, 0.06) 0%, transparent 56%)',
      pointerEvents: 'none',
      zIndex: 0,
    },
  },
  pbiHeader: {
    textAlign: 'center',
    mb: 6,
    position: 'relative',
    zIndex: 1,
    maxWidth: 820,
    mx: 'auto',
    alignItems: 'center',
  },
  pbiBadge: {
    alignSelf: 'center',
    px: 2.5,
    py: 0.8,
    borderRadius: 999,
    fontWeight: 700,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    fontSize: '0.75rem',
    color: '#1f4d70',
    background: 'rgba(124, 214, 255, 0.22)',
    border: '1px solid rgba(47, 143, 212, 0.28)',
  },
  pbiTitle: {
    fontSize: { xs: '2.4rem', md: '3.2rem' },
  },
  pbiLead: {
    color: '#2f4257',
    fontSize: { xs: '1rem', md: '1.1rem' },
    lineHeight: 1.8,
    textWrap: 'balance',
    textAlign: 'center',
    width: '100%',
  },
  pbiBody: {
    color: '#304357',
    lineHeight: 1.8,
    textWrap: 'balance',
    textAlign: 'center',
    width: '100%',
  },
  pbiGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: 'repeat(3, 1fr)' },
    gap: 3,
    position: 'relative',
    zIndex: 1,
  },
  pbiCard: {
    bgcolor: 'var(--glass)',
    borderRadius: 4,
    border: '1px solid var(--glass-border)',
    boxShadow: 'var(--glass-shadow)',
    backdropFilter: 'blur(12px)',
    height: '100%',
  },
  pbiCardTitle: {
    fontSize: '1.4rem',
    color: '#0b1b2b',
  },
  pbiCardBody: {
    color: '#304357',
  },
  pbiNote: {
    mt: 5,
    textAlign: 'center',
    color: '#4a647f',
    fontSize: '0.95rem',
    position: 'relative',
    zIndex: 1,
  },
  pbiCta: {
    mt: 3,
    position: 'relative',
    zIndex: 1,
    alignItems: 'center',
  },
  pbiButton: {
    bgcolor: '#2f8fd4',
    color: '#ffffff',
    px: 5,
    py: 1.8,
    fontWeight: 700,
    fontSize: '1.05rem',
    minWidth: { xs: '100%', sm: 240 },
    boxShadow: '0 14px 28px rgba(47, 143, 212, 0.25)',
    '&:hover': { bgcolor: '#5aa7de' },
  },
  pbiSecondaryButton: {
    borderColor: 'rgba(47, 143, 212, 0.45)',
    color: '#1f4d70',
    px: 4.5,
    py: 1.6,
    fontWeight: 700,
    fontSize: '1rem',
    minWidth: { xs: '100%', sm: 220 },
    '&:hover': { borderColor: '#2f8fd4', color: '#2f8fd4' },
  },
  climateSection: {
    py: { xs: 10, md: 14 },
    position: 'relative',
    background:
      'linear-gradient(180deg, var(--bg-section-frost) 0%, var(--bg-section-cool) 54%, var(--bg-section-base) 100%)',
    color: '#000',
    boxShadow:
      'inset 0 1px 0 rgba(255,255,255,0.85), inset 0 -1px 0 rgba(12,34,60,0.08)',
    '&::before': {
      content: '""',
      position: 'absolute',
      inset: 0,
      background:
        'radial-gradient(ellipse 102% 82% at 52% 0%, rgba(124,214,255,0.14) 0%, transparent 58%), radial-gradient(ellipse 72% 46% at 20% 100%, rgba(173,229,255,0.1) 0%, transparent 50%)',
      pointerEvents: 'none',
    },
  },
  climateIntro: {
    textAlign: 'center',
    mb: 6,
    position: 'relative',
    zIndex: 1,
  },
  climateTitle: {
    fontSize: { xs: '2.3rem', md: '3.2rem' },
    color: '#0b1b2b',
    textShadow: 'none',
  },
  climateLead: {
    color: '#304357',
    fontSize: '1.1rem',
  },
  climateMechanismGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: 'repeat(3, 1fr)' },
    gap: 3,
    mb: 6,
    position: 'relative',
    zIndex: 1,
  },
  climateMechanismCard: {
    bgcolor: 'rgba(255,255,255,0.78)',
    border: '1px solid var(--glass-border)',
    borderRadius: 4,
    boxShadow: 'var(--glass-shadow)',
    backdropFilter: 'blur(14px)',
    height: '100%',
  },
  climateMechanismCardContent: {
    p: { xs: 3, md: 4 },
  },
  climateMechanismTitle: {
    fontSize: '1.4rem',
    color: '#0b1b2b',
  },
  climateMechanismBody: {
    color: '#304357',
    lineHeight: 1.7,
  },
  climateStepNumber: {
    fontSize: '1.1rem',
    fontWeight: 700,
    color: '#2f6f9f',
  },
  climateStepIconBgSun: {
    width: 52,
    height: 52,
    borderRadius: '16px',
    display: 'grid',
    placeItems: 'center',
    bgcolor: 'rgba(245, 158, 11, 0.15)',
    border: '1px solid rgba(245,158,11,0.3)',
  },
  climateStepIconSun: {
    fontSize: 28,
    color: '#f59e0b',
  },
  climateStepIconBgWarm: {
    width: 52,
    height: 52,
    borderRadius: '16px',
    display: 'grid',
    placeItems: 'center',
    bgcolor: 'rgba(231, 111, 81, 0.12)',
    border: '1px solid rgba(231,111,81,0.3)',
  },
  climateStepIconWarm: {
    fontSize: 28,
    color: '#e76f51',
  },
  climateStepIconBgBlue: {
    width: 52,
    height: 52,
    borderRadius: '16px',
    display: 'grid',
    placeItems: 'center',
    bgcolor: 'rgba(47, 143, 212, 0.12)',
    border: '1px solid rgba(47,143,212,0.28)',
  },
  climateStepIconBlue: {
    fontSize: 28,
    color: '#2f8fd4',
  },
  climateResultSection: {
    textAlign: 'center',
    mb: 6,
    position: 'relative',
    zIndex: 1,
  },
  climateResultTitle: {
    fontSize: { xs: '1.6rem', md: '2rem' },
    mb: 4,
    color: '#0b1b2b',
  },
  climateResultGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', sm: 'repeat(3, 1fr)' },
    gap: 3,
  },
  climateResultCard: {
    bgcolor: 'rgba(255,255,255,0.8)',
    borderRadius: 4,
    border: '1px solid var(--glass-border)',
    boxShadow: 'var(--glass-shadow)',
    backdropFilter: 'blur(10px)',
    p: 3,
    textAlign: 'center',
  },
  climateResultIconBox: {
    width: 48,
    height: 48,
    borderRadius: '50%',
    display: 'grid',
    placeItems: 'center',
    bgcolor: 'rgba(124, 214, 255, 0.18)',
    mx: 'auto',
    mb: 2,
    '& svg': {
      fontSize: 24,
      color: '#7cd6ff',
    },
  },
  climateResultValue: {
    fontSize: { xs: '1.8rem', md: '2.2rem' },
    fontWeight: 700,
    color: '#2f8fd4',
    mb: 1,
  },
  climateResultLabel: {
    color: '#304357',
    fontSize: '0.95rem',
  },
  climateFeedbackDiagram: {
    bgcolor: 'rgba(255,255,255,0.9)',
    borderRadius: 5,
    border: '1px solid var(--glass-border)',
    boxShadow: 'var(--glass-shadow)',
    p: { xs: 3, md: 5 },
    textAlign: 'center',
  },
  climateFeedbackImageContainer: {
    position: 'relative',
    width: '100%',
    maxWidth: { xs: '100%', sm: 600, md: 700 },
    height: { xs: 300, sm: 400, md: 500 },
    mb: 2,
    mx: 'auto',
  },
  climateFeedbackTitle: {
    fontSize: { xs: '1.2rem', md: '1.4rem' },
    fontWeight: 600,
    mb: 4,
    color: '#1a3a5c',
  },
  climateFeedbackFlow: {
    display: 'flex',
    flexDirection: { xs: 'column', sm: 'row' },
    alignItems: 'center',
    justifyContent: 'center',
    gap: { xs: 1, sm: 2 },
    flexWrap: 'wrap',
  },
  climateFeedbackStep: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 1.5,
  },
  climateFeedbackCircle: {
    width: 64,
    height: 64,
    borderRadius: '50%',
    display: 'grid',
    placeItems: 'center',
    bgcolor: 'rgba(245, 250, 255, 1)',
    border: '2px solid rgba(47, 143, 212, 0.3)',
    boxShadow: '0 4px 12px rgba(0,0,0,0.08)',
  },
  climateFeedbackLabel: {
    fontSize: '0.9rem',
    color: '#304357',
    lineHeight: 1.4,
    textAlign: 'center',
  },
  climateFeedbackArrow: {
    fontSize: { xs: '1.5rem', sm: '2rem' },
    color: '#9eb8cf',
    fontWeight: 300,
    transform: { xs: 'rotate(90deg)', sm: 'none' },
  },
  climateFeedbackLoopIndicator: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    mt: 4,
    color: '#6a8ca8',
    '& svg': {
      animation: 'spin 3s linear infinite',
    },
    '@keyframes spin': {
      from: { transform: 'rotate(0deg)' },
      to: { transform: 'rotate(360deg)' },
    },
  },
  contactPageRoot: {
    py: { xs: 10, md: 14 },
    minHeight: '100vh',
    background:
      'linear-gradient(180deg, var(--bg-section-paper) 0%, var(--bg-section-frost) 54%, var(--bg-section-base) 100%)',
    boxShadow:
      'inset 0 1px 0 rgba(255,255,255,0.8), inset 0 -1px 0 rgba(12,34,60,0.08)',
  },
  contactHeader: {
    textAlign: 'center',
    mb: 5,
  },
  contactTitle: {
    fontSize: { xs: '2.2rem', md: '3rem' },
  },
  contactLead: {
    color: '#2f4257',
  },
  contactFrameWrap: {
    borderRadius: 5,
    overflow: 'hidden',
    border: '1px solid var(--glass-border)',
    boxShadow: 'var(--glass-shadow)',
    bgcolor: '#ffffff',
  },
  contactFrame: {
    width: '100%',
    height: { xs: 1300, md: 1601 },
    border: 0,
  },
  legalPageRoot: {
    py: { xs: 10, md: 14 },
    minHeight: '100vh',
    background:
      'linear-gradient(180deg, var(--bg-section-paper) 0%, var(--bg-section-frost) 54%, var(--bg-section-base) 100%)',
  },
  legalCard: {
    borderRadius: 6,
    border: '1px solid var(--glass-border)',
    boxShadow: 'var(--glass-shadow)',
    bgcolor: '#ffffff',
    p: { xs: 3, md: 5 },
  },
  legalTitle: {
    fontSize: { xs: '2.2rem', md: '3rem' },
    textAlign: 'center',
    mb: 4,
  },
  legalSectionTitle: {
    fontSize: { xs: '1.2rem', md: '1.4rem' },
    fontWeight: 700,
  },
  legalBody: {
    color: '#2f4257',
    lineHeight: 1.8,
  },
  articlePageRoot: {
    py: { xs: 10, md: 14 },
    minHeight: '100vh',
    background:
      'linear-gradient(180deg, var(--bg-section-paper) 0%, var(--bg-section-frost) 54%, var(--bg-section-base) 100%)',
  },
  articleHeader: {
    textAlign: 'center',
    mb: 5,
  },
  articleTitle: {
    fontSize: { xs: '2.2rem', md: '3rem' },
  },
  articleLead: {
    color: '#2f4257',
    maxWidth: 780,
    mx: 'auto',
  },
  articleGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: 'repeat(2, 1fr)' },
    gap: 3,
  },
  articleCard: {
    borderRadius: 5,
    border: '1px solid var(--glass-border)',
    boxShadow: 'var(--glass-shadow)',
    bgcolor: '#ffffff',
    height: '100%',
  },
  articleComingCard: {
    maxWidth: 760,
    mx: 'auto',
    borderRadius: 5,
    border: '1px solid rgba(47,143,212,0.24)',
    boxShadow: 'var(--glass-shadow)',
    bgcolor: 'rgba(255,255,255,0.94)',
  },
  articleCardContent: {
    p: { xs: 3, md: 4 },
  },
  articleMetaRow: {
    flexWrap: 'wrap',
  },
  articleMetaChip: {
    bgcolor: 'rgba(124,214,255,0.18)',
    color: '#1f4d70',
    border: '1px solid rgba(47,143,212,0.24)',
    fontWeight: 600,
  },
  articleCardTitle: {
    fontSize: { xs: '1.25rem', md: '1.5rem' },
    lineHeight: 1.4,
    color: '#0b1b2b',
  },
  articleCardExcerpt: {
    color: '#304357',
    lineHeight: 1.75,
  },
  articleReadButton: {
    alignSelf: 'flex-start',
    textTransform: 'none',
    fontWeight: 700,
    px: 2.5,
  },
  articleDetailTop: {
    mb: 3.5,
  },
  articleBackButton: {
    alignSelf: 'flex-start',
    px: 0,
    textTransform: 'none',
    color: '#2f6f9f',
    fontWeight: 700,
    '&:hover': { bgcolor: 'transparent', textDecoration: 'underline' },
  },
  articleDetailTitle: {
    fontSize: { xs: '2rem', md: '2.7rem' },
    lineHeight: 1.25,
  },
  articleDetailExcerpt: {
    color: '#2f4257',
    fontSize: { xs: '1rem', md: '1.05rem' },
    lineHeight: 1.8,
  },
  articleSummaryCard: {
    mb: 2.5,
    borderRadius: 5,
    border: '1px solid rgba(47,143,212,0.24)',
    boxShadow: '0 10px 26px rgba(12,34,60,0.08)',
    bgcolor: 'rgba(247,251,255,0.92)',
  },
  articleSummaryList: {
    pl: 2.5,
    m: 0,
    '& li': { mb: 0.6 },
    '& li:last-of-type': { mb: 0 },
  },
  articleBodyStack: {
    mb: 2.5,
  },
  articleSectionCard: {
    borderRadius: 5,
    border: '1px solid var(--glass-border)',
    boxShadow: '0 10px 24px rgba(12,34,60,0.08)',
    bgcolor: '#ffffff',
  },
  articleSectionTitle: {
    fontSize: { xs: '1.2rem', md: '1.35rem' },
    color: '#0b1b2b',
  },
  articleSectionBody: {
    color: '#304357',
    lineHeight: 1.8,
  },
  articleActionCard: {
    mb: 2.5,
    borderRadius: 5,
    border: '1px solid rgba(76,175,80,0.24)',
    boxShadow: '0 10px 24px rgba(76,175,80,0.08)',
    bgcolor: 'rgba(243,251,245,0.92)',
  },
  articleSourceCard: {
    borderRadius: 5,
    border: '1px solid rgba(47,143,212,0.24)',
    boxShadow: '0 10px 24px rgba(12,34,60,0.08)',
    bgcolor: '#ffffff',
  },
  articleSourceMeta: {
    color: '#5a758f',
    fontSize: '0.9rem',
  },
  articleSourceNote: {
    color: '#4a647f',
    fontSize: '0.92rem',
    lineHeight: 1.7,
  },
  articleSourceButton: {
    alignSelf: 'flex-start',
    textTransform: 'none',
    fontWeight: 700,
    px: 2.5,
  },
  homeHubSection: {
    py: { xs: 9, md: 12 },
    position: 'relative',
    background:
      'linear-gradient(180deg, var(--bg-section-frost) 0%, var(--bg-section-paper) 56%, var(--bg-section-base) 100%)',
    boxShadow:
      'inset 0 1px 0 rgba(255,255,255,0.82), inset 0 -1px 0 rgba(12,34,60,0.08)',
  },
  homeHubHeader: {
    textAlign: 'center',
    mb: 5,
  },
  homeHubTitle: {
    fontSize: { xs: '2rem', md: '2.6rem' },
  },
  homeHubLead: {
    color: '#2f4257',
    maxWidth: 720,
    mx: 'auto',
  },
  homeHubGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: 'repeat(2, 1fr)' },
    gap: 3,
  },
  homeHubCard: {
    borderRadius: 5,
    border: '1px solid var(--glass-border)',
    boxShadow: 'var(--glass-shadow)',
    bgcolor: '#ffffff',
    height: '100%',
  },
  homeHubCardContent: {
    p: { xs: 3, md: 3.5 },
  },
  homeHubIconBox: {
    width: 54,
    height: 54,
    borderRadius: '16px',
    display: 'grid',
    placeItems: 'center',
    bgcolor: 'rgba(124,214,255,0.18)',
    border: '1px solid rgba(47,143,212,0.24)',
    '& svg': {
      color: '#2f6f9f',
      fontSize: 28,
    },
  },
  homeHubCardTitle: {
    fontSize: { xs: '1.2rem', md: '1.35rem' },
    color: '#0b1b2b',
  },
  homeHubCardBody: {
    color: '#304357',
    lineHeight: 1.75,
  },
  homeHubButton: {
    alignSelf: 'flex-start',
    textTransform: 'none',
    fontWeight: 700,
    px: 2.5,
  },
  homeHubContactCta: {
    mt: 4,
    alignItems: 'center',
  },
  homeHubContactButton: {
    textTransform: 'none',
    fontWeight: 700,
    px: 3,
    py: 1.2,
    bgcolor: '#2f8fd4',
    '&:hover': { bgcolor: '#4c9fd9' },
  },
}

export default styles
